### ISSUE TITLE
RMLMapper Wrapper - Faulty behaviour when using multiple targets with same base name.

### ISSUE THREAD

**Issue by sevrijss** [RMLio/rmlmapper-java-wrapper-js#31]
# Faulty behaviour when using multiple targets with same base name.
## Description of the bug
The RMLMapper Wrapper doesn't seem to handle multiple targets with the same base name well. When 2 targets have the same base name but a different IRI, the target system seems to override targets.

## To Reproduce
When using the rules provided below (rules.yml) and the corresponding data (data.csv) in [matey](https://rml.io/yarrrml/matey/#).
Only 2 targets are visible in the output tab 
- test 
- stdout
In the `test` target, only the triples for `ratings_target` are visible, presumably because they overwrite the previous triples.

## Expected behavior
When using this config in matey, I would expect that I have 3 targets:
- http://example.com/test
- http://example2.com/test
- stdout

### rules.yml
```yaml
prefixes:
  schema: "http://schema.org/"
  dbo: "http://dbpedia.org/ontology/"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
targets:
  show_target: ["http://example.com/test~void", "turtle"]
  ratings_target: ["http://example2.com/test~void", "turtle"]
mappings:
  tv-show:
    sources:
      - ['data.csv~csv']
    s:
      - value: $(show)
        targets: show_target
    po:
      - [rdfs:label, $(title)]
      - [dbo:abstract, $(description)]
  review-show-link:
    sources:
      - ['data.csv~csv']
    s:
      - value: $(show)
        targets: ratings_target
    po:
      - [schema:review, $(review)]
  review:
    sources:
      - ['data.csv~csv']
    s:
      - value: $(review)
        targets: ratings_target
    po:
      - [schema:datePublished, $(reviewDate)]
```
### data.csv
```csv
description,score,reviewDate,title,rating,review,show
desc_mando,4,2023-06-08,The Mandalorian,http://localhost:3000/example/ratings.ttl#rating-1,http://localhost:3000/example/ratings.ttl#review-1,http://dbpedia.org/resource/The_Mandalorian
desc_got,3,2023-03-12,Game of Thrones,http://localhost:3000/example/ratings.ttl#rating-2,http://localhost:3000/example/ratings.ttl#review-2,http://dbpedia.org/resource/Game_of_Thrones
desc_op,5,2023-01-21,One Piece,http://localhost:3000/example/ratings.ttl#rating-3,http://localhost:3000/example/ratings.ttl#review-3,http://dbpedia.org/resource/One_Piece_(TV_series)
```
